swagger: "2.0"
info:
  description: "Eine kleine Demo für ein mini projektmanaagement"
  version: "1.0.3"
  title: "Project Viewer"
  contact:
    email: "Robin.seifert83@gmail.com"
basePath: "/api/v1"
tags:
- name: "demo"
  description: "nur ein test"
schemes:
- "https"
- "http"
paths:
  /project:
    post:
      tags:
      - "demo"
      description: "We add a new Project"
      operationId: "addProject"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "a new special Project"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        "204":
          description: "success"
          schema:
            $ref: "#/definitions/Project"
    get:
      tags:
      - "demo"
      description: "list all projects"
      operationId: "listProjects"
      produces:
      - "application/json"
      responses:
        "200":
          description: "all projects"
          schema:
            $ref: "#/definitions/ProjectList"
  /project/{pId}:
    parameters:
      - name: "pId"
        in: "path"
        description: "ID"
        required: true
        type: "integer"
        format: "int64"
    get:
      tags:
      - "demo"
      description: "get one project with all"
      operationId: "getProject"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/Project"
        "400":
          description: "Invalid ID supplied"
    delete:
      tags:
      - "demo"
      description: "Delete it"
      operationId: "deleteProject"
      responses:
        "204":
          description: "success"
        "404":
          description: "Project not found"
  /project/{pId}/action:
    parameters:
      - name: "pId"
        in: "path"
        description: "ID"
        required: true
        type: "integer"
        format: "int64"
    post:
      tags:
      - "demo"
      description: ""
      operationId: "addAction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "a new special Action"
        required: true
        schema:
          $ref: "#/definitions/Action"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Action"
    get:
      tags:
      - "demo"
      description: "all actions of a project"
      operationId: "listActions"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ActionList"
definitions:
  Action:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      name:
        type: "string"
      description:
        type: "string"
      time:
        type: "string"
        format: "date-time"
      projectId:
        type: "integer"
        format: "int64"
        readOnly: true
      efford:
        type: "number"
        description: "hours of work"
      members:
        type: "number"
        description: "count members in this action"
  ActionList:
    type: "object"
    properties:
      list:
        type: "array"
        items:
          $ref: "#/definitions/Action"
  ProjectList:
    type: "object"
    properties:
      list:
        type: "array"
        items:
          $ref: "#/definitions/Project"
  Project:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      name:
        type: "string"
      category:
        type: "string"
      description:
        type: "string"
      actions:
        type: "number"
        readOnly: true
      status:
        $ref: "#/definitions/ProjectStatus"
  ProjectStatus:
    type: "string"
    description: "status"
    enum:
    - "new"
    - "running"
    - "finished"